---
# tasks file for RHELEntitlementTracker
- name: Get cert info
  shell: "/opt/ansible/oc -n {{ benny_source_namespace }} get rhelentitlementtracker {{ benny_source_tracker }} -o json"
  register: entitlement_info

- name: Set entitlement var
  set_fact:
    cert_id: "{{ entitlement_info.stdout | from_json | json_query('spec.cert_id') }}"

# The cron job creates the initial Secret and CustomResource; they don't exist
# yet when the operator is first deployed.  Wait for them to be created before
# attempting any actions.
- name: Discontinue if tracker resource is not set yet; gets set by cron job
  meta: end_play
  when: cert_id = "NOT_SET_YET"

- name: Set names for Secret keys
  set_fact:
    entitlement_keypemname: "{{ cert_id }}-key.pem"
    entitlement_certpemname: "{{ cert_id }}.pem"

- name: Set query for json_query
  set_fact:
    key_query: "data.\"{{ entitlement_keypemname }}\""
    cert_query: "data.\"{{ entitlement_certpemname }}\""

- name: Get certs from Secret
  shell: "/opt/ansible/oc -n {{ benny_source_namespace }} get secret {{ benny_source_secret }} -o json"
  register: cert_info

- name: Set cert vars
  set_fact:
    entitlement_key: "{{ cert_info.stdout | from_json | json_query(key_query) }}"
    entitlement_cert: "{{ cert_info.stdout | from_json | json_query(cert_query) }}"

- name: Get project list
  shell: "/opt/ansible/oc get projects | awk '{ print $1 }' | egrep project"
  register: project_list

- name: Secret is set
  kubernetes.core.k8s:
    state: present
    api_version: v1
    apply: yes
    definition: "{{ lookup('template', 'EntitlementSecret.yaml.j2') }}"
  loop: "{{ project_list.stdout_lines }}"
  loop_control:
    loop_var: namespace

